### ISSUE TITLE
Pass config parameters/file in pytest

### ISSUE THREAD

**Issue by davidbrochart** [adriendelsalle/fps#12]
A pytest fixture for a client of an FPS app looks like this:
```python
import pytest
from fastapi.testclient import TestClient
from fps.main import app

@pytest.fixture()
def client():
    return TestClient(app)
```
It would be nice to be able to specify a config file when the app is used in pytest, and to mimic passing configuration options  through the CLI with e.g. a dictionary.

**Comment by adriendelsalle** [comment]
Hey @davidbrochart 

https://github.com/adriendelsalle/fps/pull/19 should help, let me know!

**Comment by adriendelsalle** [comment]
I just added more documentation in https://github.com/adriendelsalle/fps/pull/20
