### ISSUE TITLE
App startup/shutdown hooks

### ISSUE THREAD

**Issue by davidbrochart** [adriendelsalle/fps#9]
It would be nice to be able to add hooks on app startup/shutdown, e.g. to connect/disconnect to/from a database:

```python
@app.on_event("startup")
async def startup():
    await database.connect()

@app.on_event("shutdown")
async def shutdown():
    await database.disconnect()
```

**Comment by davidbrochart** [comment]
Actually this is already possible, since `on_event` is also available on a router.

**Comment by adriendelsalle** [comment]
Yeah totally, the `include_router` method already collects them
